In [6]:
import math

In [39]:
a = 0
b = 1
c = 1
math.atan2(b,a)

1.5707963267948966

In [38]:
c*math.sqrt((a)**2+(b)**2)

4.0

In [7]:
import numpy as np

A = np.array([[12,10,8],[-2/5,0,0],[0,15/4,0]])
b = np.array([[-2],[0],[0]])

T = np.array([[1,1,-1],[0,-1,1],[-1,0,1]])
A1 = np.dot(np.dot(T,A), np.linalg.inv(T))
np.dot(A,b)

array([[-24. ],
       [  0.8],
       [  0. ]])

In [9]:
np.dot(A, np.dot(A,b))

array([[-280. ],
       [   9.6],
       [   3. ]])

In [13]:
Wc = np.array([[-2,-24,-280],[0,4/5,48/5],[0,0,3]])
Wc1 = np.array([[1,-2,4],[0,1,-2],[0,0,1]])

np.dot(Wc,Wc1)

array([[  -2. ,  -20. , -240. ],
       [   0. ,    0.8,    8. ],
       [   0. ,    0. ,    3. ]])

In [14]:
np.linalg.inv(np.dot(Wc,Wc1))

array([[ -0.5       , -12.5       ,  -6.66666667],
       [  0.        ,   1.25      ,  -3.33333333],
       [  0.        ,   0.        ,   0.33333333]])

In [16]:
L1 = np.array([[-2,4,12]])
np.dot(L1, np.linalg.inv(np.dot(Wc,Wc1)))

array([[ 1., 30.,  4.]])