In [1]:
e = -5/12*np.log2(5/12)-7/12*np.log2(7/12)
e

NameError: name 'np' is not defined

In [ ]:
e = -2/5*np.log2(2/5)-3/5*np.log2(3/5)
e

0.9709505944546686

In [ ]:
import numpy as np

a = np.array([0.3,0.56,0.12,0,0.01,0,0.01])*100
e = np.array([0.3024,0.5040,0.108,0.072,0.009,0.0045,0.0001])*100
print(a)
print(e)
np.sum((a-e)**2/e)

[30. 56. 12.  0.  1.  0.  1.]
[3.024e+01 5.040e+01 1.080e+01 7.200e+00 9.000e-01 4.500e-01 1.000e-02]


106.42857142857142

In [ ]:
a = np.array([35,48,11,5,0,1,0])
e = np.array([0.3024,0.5040,0.108,0.072,0.009,0.0045,0.0001])*100
np.sum((a-e)**2/e)

3.1216931216931205

In [ ]:
x = np.array([-1,-0.8049,-0.7460,-0.4430,0.0938,0.2647,0.6294,0.8116,0.8268,0.915,0.9298])
y = 0.5*x+0.5
p = np.array([0,0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8,0.9,1,1])
Dplus = np.zeros(10)
Dmin = np.zeros(10)
for i in range(10):
    Dplus[i] = np.abs(y[i+1] - p[i+1])
    Dmin[i] = np.abs(p[i] - y[i+1])

print(Dplus)
print(Dplus.max())
print(Dmin)
print(Dmin.max())

[0.00245 0.073   0.0215  0.1469  0.13235 0.2147  0.2058  0.1134  0.0575
 0.0351 ]
0.2147
[0.09755 0.027   0.0785  0.2469  0.23235 0.3147  0.3058  0.2134  0.1575
 0.0649 ]
0.3147


In [ ]:
x = np.array([2.035,2.6739,3.2168,3.4517,5.1109,5.7848])
y = (x-2)/4
p = np.array([1/6,1/3,1/2,2/3,5/6,1])
Dplus = np.zeros(6)
Dmin = np.zeros(6)
for i in range(5):
    Dplus[i] = p[i] - y[i]
    if i < 5:
        Dmin[i] = y[i+1] - p[i]

print(Dplus)
print(Dplus.max())
print(Dmin)
print(Dmin.max())

[0.15791667 0.16485833 0.1958     0.30374167 0.05560833 0.        ]
0.3037416666666666
[ 0.00180833 -0.02913333 -0.137075    0.11105833  0.11286667  0.        ]
0.11286666666666656


In [ ]:
x = np.array([-0.8049,-0.7460,-0.4430,0.0938,0.2647,0.6294,0.8116,0.8268,0.915,0.9298])
y = 0.5*x+0.5
p = np.array([0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8,0.9,1])
Dplus = np.zeros(10)
Dmin = np.zeros(10)
for i in range(10):
    Dplus[i] = p[i] - y[i]
    if i < 9:
        Dmin[i] = y[i+1] - p[i]

print(Dplus)
print(Dplus.max())
print(Dmin)
print(Dmin.max())

[ 0.00245  0.073    0.0215  -0.1469  -0.13235 -0.2147  -0.2058  -0.1134
 -0.0575   0.0351 ]
0.07300000000000001
[0.027   0.0785  0.2469  0.23235 0.3147  0.3058  0.2134  0.1575  0.0649
 0.     ]
0.3147


In [ ]:
x = np.array([-4.7765,-1.9231,0.6992,2.9563,3.0279,3.6130,4.5865,7.5017])
from scipy.stats import norm

y = norm.cdf(x,loc=2,scale=3)
y

array([0.01194688, 0.09548754, 0.33228947, 0.62504827, 0.63406284,
       0.7045964 , 0.8057021 , 0.96666558])

In [ ]:
p = np.array([1/8,2/8,3/8,1/2,5/8,6/8,7/8,1])
Dplus = np.zeros(8)
Dmin = np.zeros(8)
for i in range(8):
    Dplus[i] = p[i] - y[i]
    if i < 7:
        Dmin[i] = y[i+1] - p[i]

print(Dplus)
print(Dplus.max())
print(Dmin)
print(Dmin.max())

[ 0.11305312  0.15451246  0.04271053 -0.12504827 -0.00906284  0.0454036
  0.0692979   0.03333442]
0.15451245832432664
[-0.02951246  0.08228947  0.25004827  0.13406284  0.0795964   0.0557021
  0.09166558  0.        ]
0.25004827159986864


In [ ]:
np.exp(-0.02*38)

0.46766642700990924

In [ ]:
5/60

0.08333333333333333

In [2]:
import numpy as np

# X ~ U(2,4)
# n = 200, bins = 8
# 按照假设的均匀分布每个bins应该有200/8 = 25个数据
actual = np.array([7,17,20,26,45,35,27,23])
expect = np.array([25,25,25,25,25,25,25,25])
chi_square = np.sum((actual-expect)**2/expect)
chi_square
# alpha = 0.01 critical point = 18.48
# chi square > 18.48 拒绝原假设

36.88

In [8]:
x = np.array([41.2,38.6,45,35.8,55.2,39,40.7,47.4,40.4,39.3,34.1,42,30.6,45,51.3])*10
x.var()

3800.9955555555553

In [10]:
x = np.array([358,386,386, 513,513,420,450,412,386,393,404,450,390,474,412,393,407,412,386,420,390,306,341,450,393,341,450,358,358,306,450,386,358,358,341,341,393,407,474,450,412,341,407,404,450,393,341,390,404,306,390,552,513,552,450,420,412,407,306,552,450,450,450,341,450,474,412,306,341,407,407,404,407,306,386,552,412,420,552,358,306,513,513,341,450,420,341,386,306,390,358,474,306,386,474,404,513,450,306,306,407,420,552,412,450,306,341,306,552,306,412,513,412,404,420,407,341,412,450,407,386,386,513,420,420,404,552,552,474,450,450,390,474,420,407,450,513,390,450,420,552,407,450,474,390,513,306,306,404,552])
newarr = np.array_split(x, 10)
print(newarr)
r = np.zeros(10)
d = np.zeros(10)
for i in range(10):
    d[i] = np.mean(newarr[i])
print(np.sort(d))

[array([358, 386, 386, 513, 513, 420, 450, 412, 386, 393, 404, 450, 390,
       474, 412]), array([393, 407, 412, 386, 420, 390, 306, 341, 450, 393, 341, 450, 358,
       358, 306]), array([450, 386, 358, 358, 341, 341, 393, 407, 474, 450, 412, 341, 407,
       404, 450]), array([393, 341, 390, 404, 306, 390, 552, 513, 552, 450, 420, 412, 407,
       306, 552]), array([450, 450, 450, 341, 450, 474, 412, 306, 341, 407, 407, 404, 407,
       306, 386]), array([552, 412, 420, 552, 358, 306, 513, 513, 341, 450, 420, 341, 386,
       306, 390]), array([358, 474, 306, 386, 474, 404, 513, 450, 306, 306, 407, 420, 552,
       412, 450]), array([306, 341, 306, 552, 306, 412, 513, 412, 404, 420, 407, 341, 412,
       450, 407]), array([386, 386, 513, 420, 420, 404, 552, 552, 474, 450, 450, 390, 474,
       420, 407]), array([450, 513, 390, 450, 420, 552, 407, 450, 474, 390, 513, 306, 306,
       404, 552])]
[380.73333333 398.13333333 399.26666667 399.4        414.53333333
 417.33333333 423.13333

In [77]:
417.1-29.43

387.67

In [78]:
417.1+36.37

453.47

In [37]:
y = np.array([13.95,11.01,10.41,12.87,12.36,11.17,13.5,11.89,10.09,10.28,12.7])
z = 1.64*np.sqrt(y.var()**2/11)
z

0.8073438004191565

In [38]:
y.mean() + z

12.646434709510064

In [39]:
y.mean() - z

11.031747108671752

In [45]:
1.372*np.sqrt(np.sum(y-y.mean())/110)

11.839090896762475

In [50]:
(2.872**2)*0.7962/((5/3600)**2)

3404521.15587072

In [51]:
(2.872**2)*0.0264/((5/3600)**2)

112885.40381183999

In [54]:
np.exp(-0.02*38)

0.46766642700990924

In [52]:
(2.872**2)*0.2401/((5/3600)**2)

1026658.53997056

In [57]:
x = np.array([6.6,9.13,6.9,9.63,9.32,9.82,7.7,9.79,9.75,5.66,6.86,7.04,7.85,7.74,6.53,5.61,7.25,5.25,6.55,7.34])
x.mean()
x.var()

2.0944540000000003

In [60]:
(8.43-6.802)/np.sqrt(2.4602/10+0.7217/10)

2.886098421212143

In [4]:
# 27.2
# k = 3, n0 = 20, P* = 0.95
# from table we can find that h1 = 2.872
# d* = 2 (since the mean it provided are all xx%)

s = np.array([18.1,14.8,13.1])
number = (2.872**2)*(s**2)/(2**2) # h1^2*s1^2 / d*^2
number - 20

array([655.56327056, 431.68150784, 333.87629456])

In [136]:
t1 = np.array([2699,2778,3037,902,5285,4172,3092,5217,2135,3744,3605,4166,4159,2982,3816,3682,4474,4940,4956,2983])
t2 = np.array([4151,3211,4297,2638,2007,1981,3891,3225,3206,4823,3694,3600,4990,2598,4099,4238,3159,3618,2237,2255])

In [133]:
z = t1-t2
z

array([-1452,  -433, -1260, -1736,  3278,  2191,  -799,  1992, -1071,
       -1079,   -89,   566,  -831,   384,  -283,  -556,  1315,  1322,
        2719,   728])

In [134]:
z.mean() - 1.729*np.sqrt(np.sum((z-z.mean())**2) / (20*19))

-323.409271236886

In [135]:
z.mean() + 1.729*np.sqrt(np.sum((z-z.mean())**2) / (20*19))

814.009271236886

In [141]:
(2.453**2)*t1.var()/10000

695.0748649616639

In [142]:
2.453**2*t2.var()/10000

467.25745340847095

#### PPT里的例题

In [119]:
t1 = np.array([2.127,4.2164,4.3521,5.4543,3.527])
t2 = np.array([4.5409,4.7218,4.1447,1.8607,1.3491])
z = t1-t2
z

array([-2.4139, -0.5054,  0.2074,  3.5936,  2.1779])

In [130]:
z.mean() - 2.132*np.sqrt(np.sum((z-z.mean())**2) / 20)

-1.6195791307588814

In [131]:
z.mean() + 2.132*np.sqrt(np.sum((z-z.mean())**2) / 20)

2.8434191307588814

### 25.2

In [7]:
x= np.array([13.95,11.01,10.41,12.87,12.36,11.17,13.5,11.89,10.09,10.28,12.7])
1.812*np.sqrt(x.var()/len(x))

0.6980995456794369

In [8]:
11.84 - 1.812*np.sqrt(x.var()/len(x))

11.141900454320563